name 'a2tar-monit'
version '0.1.1'
author 'A2taR'
license 'MIT License'
source 'https://github.com/a2tar/monit.git'
project_page 'https://github.com/a2tar/monit'
summary 'Monit on ubuntu'
dependency 'puppetlabs-apt', '>= 1.2.0'
